### ISSUE TITLE
이 남자 뭘 만들까...?

### ISSUE THREAD

**Issue by JustKode** [FacerAin/facerain-blog#1]
![image](https://user-images.githubusercontent.com/28499550/128505805-351ce6ca-00ad-4857-b0b8-9ab33bba2325.png)
기대가 됩니다.

**Comment by FacerAin** [comment]
포트폴리오에 Google AD를 넣는 개발자가 있다?

**Comment by JJuOn** [comment]
![image](https://user-images.githubusercontent.com/43328935/128622353-cc4d6949-6986-4c3a-8d81-cf2bbd6871cc.png)
